version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
python:
  install:
    - path: .
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
