name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: read
    with:
      standard-maintenance-scripts-extras: erd,perf
      # click and libcove are used by manage.py. test_requirements.py ignores try/except blocks (orjson).
      standard-maintenance-scripts-ignore: click,libcove,orjson
